### ISSUE TITLE
Having Issue with map

### ISSUE THREAD

**Issue by flavious27** [Wintervorst/iitc#9] opened 2024-09-03 02:44 UTC
I have used this before on a different device and tried to install the plugins and get this up and running but the map is not changing to show the cells.

**Comment by jjfoid** [comment] 2024-11-08 09:52
Doesn't work for me either. Not sure if it's still supported.

**Comment by Wintervorst** [comment] 2024-11-10 09:38
Can you provide me with more details on which browser/app you are using and about any other plugins you have installed at the same time?

**Comment by jjfoid** [comment] 2024-11-10 09:58
> Can you provide me with more details on which browser/app you are using and about any other plugins you have installed at the same time?

Browser - Google Chrome 130.0.6723.117 (64-bit)
App - IITC button from Chrome Web Store (https://chromewebstore.google.com/detail/iitc-button/febaefghpimpenpigafpolgljcfkeakn) - IITC 0.39.1 at the moment
Other plugins - no custom plugins, only the standard set that came in a bundle.

The Submitrange plugin works just fine, while occupied19cells.user.js (together with S2 Celldrawer for sure) doesn't work at all. There are no additional layers in the menu, and there are no polygons on the map.

**Comment by jjfoid** [comment] 2024-11-10 10:06
What is interesting... I have both occupied19cells.user.js and S2 Celldrawer enabled
![image](https://github.com/user-attachments/assets/bde3ad11-bf73-4f18-9ccf-6da8917351a7)

but they don't appear in the list of plugins:
![image](https://github.com/user-attachments/assets/d7262521-1f27-46d3-bfbc-50d063d1ec75)
Which means to me that they didn't get initialized.
If I add the Submitrange plugin and switch it on - it appears in the list.

**Comment by Wintervorst** [comment] 2024-11-10 10:33
There is a maximum zoom level for this script. It won't work if you are zoomed out too much since that will require your browser to draw too many cells.
Zoomlevel should be 15 or higher.
For instance, does this link for you: 
https://intel.ingress.com/intel?ll=52.268174,6.791767&z=17

**Comment by jjfoid** [comment] 2024-11-10 10:45
> There is a maximum zoom level for this script. It won't work if you are zoomed out too much since that will require your browser to draw too many cells. Zoomlevel should be 15 or higher. For instance, does this link for you: https://intel.ingress.com/intel?ll=52.268174,6.791767&z=17

Oh, it seems like I found the root cause of the issue.
You provided the link
https://intel.ingress.com/intel?ll=52.268174,6.791767&z=17
And it works fine.
while inside IITC permalinks by default use another pattern, i.e.
https://intel.ingress.com/?ll=52.268174,6.791767&z=17
(without "intel" after /)|
And it's not a part of the script:
`// @include        https://*.ingress.com/intel*
// @include        http://*.ingress.com/intel*
// @match          https://*.ingress.com/intel*
// @match          http://*.ingress.com/intel*
// @include        https://*.ingress.com/mission/*
// @include        http://*.ingress.com/mission/*
// @match          https://*.ingress.com/mission/*
// @match          http://*.ingress.com/mission/*`

So I assume one more line should be added in the script's header to catch this.

**Comment by Wintervorst** [comment] 2024-11-10 10:59
Ah, I thought we had this already covered with a previous PR a few years back, but that only fixed it for one of the plugins and not all of them.
I will change it for all other plugins.

**Comment by jjfoid** [comment] 2024-11-10 11:02
Perfect, thanks!

**Comment by Wintervorst** [comment] 2024-11-10 11:14
Please let me know if this fix solves your issues

**Comment by jjfoid** [comment] 2024-11-10 11:33
Confirmed. Works great now!
Thank you!

**Comment by Wintervorst** [comment] 2024-11-10 11:37
> Confirmed. Works great now! Thank you!

Nice, I will close this issue then.
One last question for you out of curiosity; for which purpose are you planning to use this plugin? This helps me better understand why I should maintain it. My personal use for it has unfortunately somewhat faded.
You can reach me on telegram @Wintervorst

**Closed as completed** 2024-11-22 07:45 UTC
